version: '3.7'
volumes: 
  prometheus_data:
  nodejs_data:

networks: 
  backend:
    driver: bridge
    ipam:
      config: 
        - subnet: 172.16.238.0/24

services: 
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports: 
      - 3000:3000
    networks: 
      - backend
    restart: on-failure
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports: 
      - 9090:9090
    volumes: 
      - prometheus_data:/prometheus
      - type: bind
        source: ./services/configs/prometheus.yml
        target: /etc/prometheus/prometheus.yml
    networks:
      backend:
        ipv4_address: 172.16.238.9
    restart: on-failure
  nodejs:
    container_name: nodejs
    image: msimou/nodejs
    build: 
      context: ./services
      dockerfile: ./nodejs/deployments/nodejs.dockerfile
    ports: 
      - 8000:8000
    environment: 
      - PORT=8000
    volumes: 
      - type: bind
        source: ./services/nodejs
        target: /nodejs
    networks: 
      backend:
        ipv4_address: 172.16.238.10
    restart:  on-failure